import React, { useEffect, useMemo, useState } from 'react';
import { api } from './services/api';
import { clearSession, getUser, saveSession } from './services/auth';
import UserDashboardFixed from './UserDashboard';

const money = n => Number(n || 0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const date = v => new Date(v).toLocaleString();
const emptyProduct={name:'',sku:'',description:'',wholesalePrice:'',retailPrice:'',openingStock:0,lowStockThreshold:0,active:true,priceNote:''};
const emptyFilters={from:'',to:'',productId:'',userId:'',type:''};

function Login({onLogin}){const [mode,setMode]=useState('login'),[name,setName]=useState(''),[username,setUsername]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[error,setError]=useState('');async function submit(e){e.preventDefault();setError('');if(mode==='register'&&password!==confirmPassword){setError('Passwords do not match.');return}try{const endpoint=mode==='register'?'/auth/register':'/auth/login';const body=mode==='register'?{name,username,email,password}:{identifier:username,password};const {data}=await api.post(endpoint,body);saveSession(data);onLogin(data.user)}catch(err){setError(err.response?.data?.message||(mode==='register'?'Account creation failed.':'Login failed.'))}}return <main className="page"><section className="card"><h1>Inventory & Sales Management</h1><p>{mode==='login'?'Sign in to continue.':'Create an account to record sales.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label>}<label>{mode==='login'?'Username or email':'Username'}<input required type={mode==='login'?'text':'text'} value={mode==='login'?username:username} onChange={e=>setUsername(e.target.value)} /></label>{mode==='register'&&<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode==='register'&&<label>Password<input required minLength="8" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==='login'&&<label>Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==='register'&&<label>Confirm password<input required minLength="8" type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label>}<button>{mode==='login'?'Sign in':'Create account'}</button>{error&&<p className="error">{error}</p>}</form><button className="auth-toggle" type="button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?<>Don't have an account? <span className="auth-toggle-label">Create one</span></>:<>Already have an account? <span className="auth-toggle-label">Sign in</span></>}</button></section></main>}

function AdminDashboard({user,logout}){
 const [summary,setSummary]=useState(null),[products,setProducts]=useState([]),[sales,setSales]=useState([]),[users,setUsers]=useState([]),[movements,setMovements]=useState([]),[alerts,setAlerts]=useState([]),[tab,setTab]=useState('overview'),[editing,setEditing]=useState(null),[history,setHistory]=useState([]),[historyOpen,setHistoryOpen]=useState(false),[message,setMessage]=useState('');
 const [stockForm,setStockForm]=useState({productId:'',quantity:'',note:''});
 const [productForm,setProductForm]=useState(emptyProduct); const [filters,setFilters]=useState(emptyFilters); const [report,setReport]=useState(null); const [reportKind,setReportKindState]=useState('sales'); function setReportKind(kind){setReportKindState(kind);setReport(null)}
 async function load(){const [s,p,v,m,a]=await Promise.all([api.get('/dashboard/admin/summary'),api.get('/products'),api.get('/sales'),api.get('/inventory/movements'),api.get('/reports/stock-alerts')]);setSummary(s.data);setProducts(p.data);setSales(v.data);setMovements(m.data);setAlerts(a.data);setUsers([...new Map(v.data.map(x=>[x.user.id,x.user])).values()])}
 useEffect(()=>{load().catch(e=>setMessage(e.response?.data?.message||'Failed to load dashboard.'))},[]);
 async function addProduct(e){e.preventDefault();try{await api.post('/products',productForm);setProductForm(emptyProduct);setMessage('Product created.');await load()}catch(e){setMessage(e.response?.data?.message||'Could not create product.')}}
 async function updateProduct(e){e.preventDefault();try{await api.put(`/products/${editing.id}`,editing);setEditing(null);setMessage('Product updated. Past sale prices remain unchanged.');await load()}catch(e){setMessage(e.response?.data?.message||'Could not update product.')}}
 async function deleteProduct(id){if(!window.confirm('Delete this product? Products with sales or stock movements cannot be deleted.'))return;try{await api.delete(`/products/${id}`);setMessage('Product deleted.');await load()}catch(e){setMessage(e.response?.data?.message||'Could not delete product.')}}
 async function deleteSale(id){if(!window.confirm('Delete this sale and restore its stock?'))return;try{await api.delete(`/sales/${id}`);setMessage('Sale deleted and stock restored.');await load()}catch(e){setMessage(e.response?.data?.message||'Could not delete sale.')}}
 async function deleteStockIn(id){if(!window.confirm('Delete this stock receipt and restore the previous stock level?'))return;try{await api.delete(`/inventory/stock-in/${id}`);setMessage('Stock receipt deleted.');await load()}catch(e){setMessage(e.response?.data?.message||'Could not delete stock receipt.')}}
 async function showHistory(id){const {data}=await api.get(`/products/${id}/price-history`);setHistory(data);setHistoryOpen(true);}
 async function stockIn(e){e.preventDefault();try{await api.post('/inventory/stock-in',stockForm);setStockForm({productId:'',quantity:'',note:''});setMessage('Stock received.');await load()}catch(e){setMessage(e.response?.data?.message||'Stock-in failed.')}}
 async function runReport(){const qs=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const {data}=await api.get(`/reports/${reportKind}?${qs}`);setReport(data);}
 async function exportFile(kind,format){try{const qs=new URLSearchParams(Object.entries({...filters,format}).filter(([,v])=>v));const response=await api.get(`/reports/${kind}/export?${qs.toString()}`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=`${kind}-report.${format==='xlsx'?'xlsx':format}`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch(e){setMessage(e.response?.data?.message||'Export failed.')}}
 if(!summary)return <div className="loading">Loading dashboard…</div>;
 return <div className="app"><header className="topbar"><div><strong>Inventory & Sales</strong><span>Admin Dashboard</span></div><div>{user.name} <button onClick={logout}>Logout</button></div></header><nav className="tabs">{[['overview','Overview'],['products','Products'],['stock','Inventory'],['sales','Sales'],['reports','Reports']].map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav><main className="content">{message&&<div className="alert info">{message}</div>}
 {tab==='overview'&&<><div className="metrics">{[['Products',summary.metrics.totalProducts],['Sales',summary.metrics.totalSales],['Revenue',money(summary.metrics.totalRevenue)],['Gross Profit',money(summary.metrics.totalGrossProfit)],['Variance',money(summary.metrics.totalVariance)],['Out of Stock',summary.metrics.outOfStockCount],['Low Stock',summary.metrics.lowStockCount]].map(([k,v])=><div className="metric" key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><section className="panel"><h2>Stock Alerts</h2>{alerts.length?<div className="alert-grid">{alerts.map(a=><div className={a.status==='OUT_OF_STOCK'?'alert danger':'alert warning'} key={a.id}><b>{a.name}</b><span>{a.status==='OUT_OF_STOCK'?'OUT OF STOCK':`LOW STOCK: ${a.currentStock} units`}</span><small>Threshold: {a.lowStockThreshold}</small></div>)}</div>:<p>No stock alerts.</p>}</section><h2>Current Inventory</h2><InventoryTable inventory={summary.inventory}/></>}
 {tab==='products'&&<><h2>Products</h2><form className="inline-form" onSubmit={addProduct}><input required placeholder="Name" value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})}/><input required placeholder="SKU" value={productForm.sku} onChange={e=>setProductForm({...productForm,sku:e.target.value})}/><input required type="number" step="0.01" min="0" placeholder="Wholesale" value={productForm.wholesalePrice} onChange={e=>setProductForm({...productForm,wholesalePrice:e.target.value})}/><input required type="number" step="0.01" min="0" placeholder="Retail" value={productForm.retailPrice} onChange={e=>setProductForm({...productForm,retailPrice:e.target.value})}/><input type="number" min="0" placeholder="Opening stock" value={productForm.openingStock} onChange={e=>setProductForm({...productForm,openingStock:e.target.value})}/><input type="number" min="0" placeholder="Low-stock threshold" value={productForm.lowStockThreshold} onChange={e=>setProductForm({...productForm,lowStockThreshold:e.target.value})}/><button>Add Product</button></form><ProductTable products={products} onEdit={setEditing} onHistory={showHistory} onDelete={deleteProduct}/></>}
 {tab==='stock'&&<><h2>Receive Stock</h2><form className="inline-form" onSubmit={stockIn}><select required value={stockForm.productId} onChange={e=>setStockForm({...stockForm,productId:e.target.value})}><option value="">Select product</option>{products.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input required type="number" min="1" placeholder="Quantity" value={stockForm.quantity} onChange={e=>setStockForm({...stockForm,quantity:e.target.value})}/><input placeholder="Note" value={stockForm.note} onChange={e=>setStockForm({...stockForm,note:e.target.value})}/><button>Record Stock In</button></form><h2>Inventory Movement History</h2><MovementTable rows={movements} onDeleteStockIn={deleteStockIn}/></>}
 {tab==='sales'&&<><div className="section-head"><h2>Detailed Sales</h2><button onClick={()=>exportFile('sales','csv')}>Export CSV</button><button onClick={()=>exportFile('sales','xlsx')}>Export Excel</button><button onClick={()=>exportFile('sales','pdf')}>Export PDF</button></div><SalesTable sales={sales} onDelete={deleteSale}/></>}
 {tab==='reports'&&<Reports products={products} users={users} filters={filters} setFilters={setFilters} reportKind={reportKind} setReportKind={setReportKind} report={report} runReport={runReport} exportFile={exportFile}/>} 
 </main>{editing&&<ProductEditor product={editing} setProduct={setEditing} onSave={updateProduct} onClose={()=>setEditing(null)}/>} {historyOpen&&<HistoryPanel rows={history} onClose={()=>setHistoryOpen(false)}/>}</div>
}

function ProductTable({products,onEdit,onHistory,onDelete}){return <div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Wholesale</th><th>Retail</th><th>Stock</th><th>Threshold</th><th>Status</th><th>Actions</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.sku}</td><td>{money(p.wholesalePrice)}</td><td>{money(p.retailPrice)}</td><td>{p.openingStock}</td><td>{p.lowStockThreshold}</td><td>{!p.active?'Inactive':p.openingStock===0?'Out of stock':p.openingStock<=p.lowStockThreshold?'Low stock':'Active'}</td><td><button onClick={()=>onEdit({...p,priceNote:''})}>Edit</button> <button onClick={()=>onHistory(p.id)}>Price history</button> <button onClick={()=>onDelete(p.id)}>Delete</button></td></tr>)}</tbody></table></div>}
function ProductEditor({product,setProduct,onSave,onClose}){return <div className="modal-backdrop"><section className="modal"><h2>Edit Product</h2><p className="muted">Stock is intentionally not editable here. Inventory changes must be recorded as movements.</p><form onSubmit={onSave}><label>Name<input required value={product.name} onChange={e=>setProduct({...product,name:e.target.value})}/></label><label>SKU<input required value={product.sku} onChange={e=>setProduct({...product,sku:e.target.value})}/></label><label>Description<textarea value={product.description||''} onChange={e=>setProduct({...product,description:e.target.value})}/></label><div className="two"><label>Wholesale<input type="number" step="0.01" min="0" value={product.wholesalePrice} onChange={e=>setProduct({...product,wholesalePrice:e.target.value})}/></label><label>Retail<input type="number" step="0.01" min="0" value={product.retailPrice} onChange={e=>setProduct({...product,retailPrice:e.target.value})}/></label></div><label>Low-stock threshold<input type="number" min="0" value={product.lowStockThreshold} onChange={e=>setProduct({...product,lowStockThreshold:e.target.value})}/></label><label>Price change note<textarea placeholder="Optional audit note" value={product.priceNote||''} onChange={e=>setProduct({...product,priceNote:e.target.value})}/></label><label className="check"><input type="checkbox" checked={product.active!==false} onChange={e=>setProduct({...product,active:e.target.checked})}/> Active</label><div className="actions"><button type="button" onClick={onClose}>Cancel</button><button>Save changes</button></div></form></section></div>}
function HistoryPanel({rows,onClose}){return <div className="modal-backdrop"><section className="modal wide"><h2>Price History</h2><table><thead><tr><th>Date</th><th>Change</th><th>Old Wholesale</th><th>Old Retail</th><th>New Wholesale</th><th>New Retail</th><th>Changed By</th><th>Note</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{date(r.createdAt)}</td><td>{r.changeType}</td><td>{money(r.previousWholesale)}</td><td>{money(r.previousRetail)}</td><td>{money(r.newWholesale)}</td><td>{money(r.newRetail)}</td><td>{r.changedBy.name}</td><td>{r.note||''}</td></tr>)}</tbody></table><button onClick={onClose}>Close</button></section></div>}
function InventoryTable({inventory}){return <div className="table-wrap"><table><thead><tr><th>Product</th><th>Stock</th><th>Wholesale</th><th>Retail</th><th>Cost Value</th><th>Retail Value</th><th>Potential Profit</th><th>Status</th></tr></thead><tbody>{inventory.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.currentStock}</td><td>{money(p.wholesaleUnitPrice)}</td><td>{money(p.retailUnitPrice)}</td><td>{money(p.totalCostValue)}</td><td>{money(p.expectedRetailValue)}</td><td>{money(p.expectedProfit)}</td><td>{p.outOfStock?<b className="danger">OUT OF STOCK</b>:p.lowStock?<b className="warning">LOW STOCK</b>:'OK'}</td></tr>)}</tbody></table></div>}
function MovementTable({rows,onDeleteStockIn}){return <div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Product</th><th>Qty</th><th>Before</th><th>After</th><th>Unit Cost</th><th>Retail Value</th><th>User</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{date(r.createdAt)}</td><td>{r.type}</td><td>{r.product.name}</td><td>{r.quantity}</td><td>{r.stockBefore}</td><td>{r.stockAfter}</td><td>{money(r.wholesaleUnitPrice)}</td><td>{money(r.expectedRetailValue)}</td><td>{r.user.name}</td><td>{r.type==='STOCK_IN'&&<button onClick={()=>onDeleteStockIn(r.stockInId)}>Delete</button>}</td></tr>)}</tbody></table></div>}
function SalesTable({sales,onDelete}){return <div className="table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>SKU</th><th>Qty</th><th>Retail</th><th>Expected</th><th>Paid</th><th>Payment</th><th>M-Pesa Receipt</th><th>Variance</th><th>Reason</th><th>COGS</th><th>Profit</th><th>User</th><th>Actions</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td>{date(s.createdAt)}</td><td>{s.product.name}</td><td>{s.product.sku}</td><td>{s.quantity}</td><td>{money(s.retailUnitPrice)}</td><td>{money(s.expectedTotal)}</td><td>{money(s.actualAmountPaid)}</td><td>{s.paymentMethod}</td><td>{s.mpesaReceiptNumber||'—'}</td><td>{money(s.salesVariance)}</td><td>{s.varianceReason||'—'}</td><td>{money(s.costOfGoodsSold)}</td><td>{money(s.grossProfit)}</td><td>{s.user.name}</td><td><button onClick={()=>onDelete(s.id)}>Delete</button></td></tr>)}</tbody></table></div>}
function Reports({products,users,filters,setFilters,reportKind,setReportKind,report,runReport,exportFile}){return <section><h2>Reporting</h2><div className="filters"><label>From<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>To<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><label>Product<select value={filters.productId} onChange={e=>setFilters({...filters,productId:e.target.value})}><option value="">All</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>User<select value={filters.userId} onChange={e=>setFilters({...filters,userId:e.target.value})}><option value="">All</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Type / variance reason<select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">All</option><option value="DISCOUNT">Discount</option><option value="ERROR">Error</option><option value="NEGOTIATION">Negotiation</option><option value="FRAUD">Fraud</option><option value="OTHER">Other</option></select></label><label>Report<select value={reportKind} onChange={e=>setReportKind(e.target.value)}><option value="sales">Sales / Variance</option><option value="profit">Profit by Product</option></select></label><button onClick={runReport}>Run Report</button></div>{report&&<><div className="metrics">{[['Quantity',report.totals.quantity],['Revenue',money(report.totals.revenue)],['COGS',money(report.totals.cogs)],['Gross Profit',money(report.totals.profit)],['Variance',money(report.totals.variance)],['Margin',`${Number(report.totals.marginPercent||0).toFixed(2)}%`]].map(([k,v])=><div className="metric" key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><div className="export-row"><button onClick={()=>exportFile(reportKind,'csv')}>CSV</button><button onClick={()=>exportFile(reportKind,'xlsx')}>Excel</button><button onClick={()=>exportFile(reportKind,'pdf')}>PDF</button></div>{reportKind==='sales'?<SalesTable sales={report.rows}/>:<div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Qty</th><th>Revenue</th><th>COGS</th><th>Profit</th><th>Margin</th><th>Variance</th></tr></thead><tbody>{report.rows.map(r=><tr key={r.productId}><td>{r.product}</td><td>{r.sku}</td><td>{r.quantity}</td><td>{money(r.revenue)}</td><td>{money(r.cogs)}</td><td>{money(r.profit)}</td><td>{Number(r.marginPercent).toFixed(2)}%</td><td>{money(r.variance)}</td></tr>)}</tbody></table></div>}</>}</section>}

function UserDashboard({user,logout}){const [products,setProducts]=useState([]),[form,setForm]=useState({productId:'',quantity:1,actualAmountPaid:''}),[search,setSearch]=useState(''),[message,setMessage]=useState('');async function load(){const {data}=await api.get('/products');setProducts(data)}useEffect(()=>{load()},[]);const product=products.find(p=>p.id===Number(form.productId));const visibleProducts=products.filter(p=>{const query=search.trim().toLowerCase();return !query||p.name.toLowerCase().includes(query)||p.sku.toLowerCase().includes(query)});const expected=product?Number(form.quantity||0)*Number(product.retailPrice):0;const variance=expected-Number(form.actualAmountPaid||0);async function sell(e){e.preventDefault();const body={...form,productId:Number(form.productId),quantity:Number(form.quantity),actualAmountPaid:Number(form.actualAmountPaid)};if(variance!==0){const reason=window.prompt('Reason: DISCOUNT, ERROR, NEGOTIATION, FRAUD, or OTHER');if(!reason)return;body.varianceReason=reason.toUpperCase()}try{const {data}=await api.post('/sales',body);setMessage(`Sale recorded. Remaining stock: ${data.stockAfter}.`);setForm({productId:'',quantity:1,actualAmountPaid:''});load()}catch(err){setMessage(err.response?.data?.message||'Sale failed.')}}return <div className="app"><header className="topbar"><div><strong>Inventory & Sales</strong><span>Sales Dashboard</span></div><div>{user.name} <button onClick={logout}>Logout</button></div></header><main className="content narrow"><section className="panel"><h2>Record Sale</h2><form onSubmit={sell}><label>Search product<input type="search" placeholder="Name or SKU" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Product<select required value={form.productId} onChange={e=>setForm({...form,productId:e.target.value})}><option value="">Select product</option>{visibleProducts.map(p=><option disabled={!p.active||p.openingStock===0} key={p.id} value={p.id}>{p.name} ({p.sku}) — {p.openingStock} units — {money(p.retailPrice)}</option>)}</select></label>{product&&<div className={product.openingStock===0?'alert danger':'alert'}>{product.openingStock===0?'OUT OF STOCK — 0 UNITS REMAINING':`Available: ${product.openingStock} units | Unit retail price: ${money(product.retailPrice)}`}</div>}<label>Quantity<input required type="number" min="1" max={product?.openingStock||undefined} value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Expected total<input readOnly value={money(expected)}/></label><label>Actual amount paid<input required type="number" step="0.01" min="0" value={form.actualAmountPaid} onChange={e=>setForm({...form,actualAmountPaid:e.target.value})}/></label>{form.actualAmountPaid!==''&&<div className={variance===0?'alert':'alert warning'}>Variance: {money(variance)} {variance!==0&&'(reason required)'}</div>}<button>Record Sale</button>{message&&<p>{message}</p>}</form></section></main></div>}
function App(){const [user,setUser]=useState(getUser());function logout(){clearSession();setUser(null)}if(!user)return <Login onLogin={setUser}/>;return user.role==='ADMIN'?<AdminDashboard user={user} logout={logout}/>:<UserDashboardFixed user={user} logout={logout}/>}
export default App;
